-- 创建一个简单的 posts 表
create table posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text
);

-- 插入一条初始数据
insert into posts (title, content)
values ('Hello Mota Nucleus', 'The database connection is working perfectly.');

-- 开启 Row Level Security (RLS) -这是 Supabase 的安全基石
alter table posts enable row level security;

-- 允许所有人读取 (为了测试方便)
create policy "Public posts are visible to everyone."
  on posts for select
  to anon
  using ( true );